steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/jenkinsxio-labs/jxl:${_VERSION}', '.' ]
substitutions:
  _VERSION: 0.0.1
timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
images:
- 'gcr.io/jenkinsxio-labs/jxl:${_VERSION}'